name: CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v5
    - name: Test
      run: sbt test
    - name: Format Check
      run: sbt scalafmtCheck
