name: Scalafmt
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v5
    - name: Scalafmt Check
      run: sbt scalafmtCheck
